language: python

python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6-dev'

cache: pip

services:
  - mysql

env:
  - DJANGO=1.8.16

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt



before_script:
  - mysql -e 'create database lurker;'

script:
  - ./tools/pre-tests.sh
  - cd ${TRAVIS_BUILD_DIR}/src
  - python manage.py migrate
  - python manage.py createcachetable
  - coverage run manage.py test


after_success:
  - coveralls


matrix:
  fast_finish: true
  allow_failures:
    - python: '3.6-dev'
