language: python

python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6-dev'

services:
  - mysql

env:
  - DJANGO=1.8.15

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt



before_script:
  - mysql -e 'create database lurker;'

script:
  - ./tools/pre-tests.sh
  - cd src && python manage.py migrate
  - cd src && python manage.py createcachetable
  - cd src && python manage.py test


after_success:
  - bash <(curl -s https://codecov.io/bash)


matrix:
  fast_finish: true
  allow_failures:
    - python: '3.6-dev'
